### ISSUE TITLE
Windows cuda issue

### ISSUE THREAD

**Issue by elich11** [h2oai/h2ogpt#399]
Try to install on 2 separate windows machines (10, 11).
In both cases for an error:
CUDA Setup failed despite GPU being available.
Here is the full issue log (TLDR: it can't find libbitsandbytes_cuda121.dll although it exists in this location):
python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin D:\projects\llm_gpu\gpu\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
False
CUDA SETUP: CUDA runtime path found: D:\Program Files\cuda\bin\cudart64_12.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary D:\projects\llm_gpu\gpu\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll...
Could not find module 'D:\projects\llm_gpu\gpu\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by pseudotensor** [comment]
Hi, did you try following the windows specific instructions? https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md

That is what worked for me, using the bitsandbytes linked there.

**Comment by elich11** [comment]
Thanks,
 I did, on 2 independent machines.
Anyway, maybe I missed something. I will try again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md
