### ISSUE TITLE
Multiple GPU

### ISSUE THREAD

**Issue by pd-vt** [h2oai/h2ogpt#428]
We have multiple number of 3070 TI GPUs which is of 8GB each, They are well detecting in OS but H2O process only loads the code in single GPU (confirmed via NVITOP command in ubuntu) and than out of memory error comes because of 8GB is not enough. 
How can we use multiple GPUs ?

**Comment by pseudotensor** [comment]
Pass `--infer_devices=False` .  It's a bad name and only indirectly related, but I should change it and cleanup related code to avoid confusions.

**Comment by pd-vt** [comment]
Thank you @pseudotensor This solution has worked for me and also later on I realised that even chat UI provides and option to finetune this setting. Thank you again.

**Comment by pseudotensor** [comment]
@pd-vt FYI we changed infer_devices to better name.
