### ISSUE TITLE
0% GPU usage WINDOWS 11

### ISSUE THREAD

**Issue by Frub3L** [h2oai/h2ogpt#437]
Hello, I managed to run the script successfully using the:
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --langchain_mode=MyData --score_model=None --share=False --prompt_type=human_bot --gradio_offline_level=1 --load_4bit=True

However, today I installed new cuda drivers and something went wrong and after I run the command my GPU is on 0%. 
Any ideas what could go wrong?
Thank you!
![image](https://github.com/h2oai/h2ogpt/assets/139390959/2639c462-47c0-4494-a76f-d8b69829bd7e)

**Comment by pseudotensor** [comment]
Hi, I can't tell what could have gone wrong.  You can do things like docs/README_GPU.md (https://github.com/h2oai/h2ogpt/blob/162900fba8b03fa30a5a41fd8e11bb8a34131d2f/docs/README_GPU.md) shows, like:

```python
import torch
print(torch.cuda.is_available())
```
should print True.

**Comment by Frub3L** [comment]
> 

After trying to modify the cuda version, I started getting this error:
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
        
        
        
After that I reinstalled my GPU drivers and h2ogpt, then it worked, but my GPU usage is now on 0%.

After running the: 
import torch
print(torch.cuda.is_available())
by reading the .py file, it actually says CPU, which would print False for the GPU usage.
I am confused and have no idea how to fix the issue, I am hoping someone had a similar issue.

**Comment by pseudotensor** [comment]
For bitsandbytes, did you use the windows installation direction's version of that package?

**Comment by Frub3L** [comment]
> For bitsandbytes, did you use the windows installation direction's version of that package?

Yes, I followed the steps for Windows section. It worked fine just yesterday, can't get it to work now no matter what I do.

**Comment by pseudotensor** [comment]
I revamped and fully tested the docs for windows, please try again: https://github.com/h2oai/h2ogpt/blob/main/docs/README_WINDOWS.md

**Comment by DuuuDik** [comment]
solution for me was reinstalling cuda drivers 
hope this helps to future readers
