### ISSUE TITLE
High CPU Usage and Low GPU Usage with llama-2-7b-chat.ggmlv3.q8_0.bin Model

### ISSUE THREAD

**Issue by quartet** [h2oai/h2ogpt#592]
Greetings,

I am currently using your application with the llama-2-7b-chat.ggmlv3.q8_0.bin model. While running the application, I've noticed that the system's CPU load is consistently high (around 98%), while the GPU load remains significantly low. I've confirmed that my GPU is properly installed and recognized by PyTorch (torch.cuda.is_available() returns True).

Here is the script that I'm using to run the application:

#!/bin/bash

# Run generate.py with the specified parameters
python generate.py \
    --base_model='llama' \
    --prompt_type='llama2' \
    --temperature=0.8 \
    --top_p=0.85 \
    --top_k=50 \
    --num_beams=2 \
    --max_new_tokens=1024 \
    --repetition_penalty=1.1 \
    --early_stopping=True \
    --max_time=180 \
    --num_doc_chunks=3 \
    --chunk_size=1024 \
    --langchain_mode='UserData' \
    --share=False \
    --gradio_offline_level=1
    
![no-cpu](https://github.com/h2oai/h2ogpt/assets/894042/39aa3ce9-5ce3-4294-97ca-a2bc90d7606f)

This is not the expected behavior, as I believe the GPU should be utilized more extensively for this type of workload. This high CPU load and low GPU load is affecting the performance of my system and the efficiency of running the model.

I've attached a screenshot of the system CPU and GPU load while running the llama-2-7b-chat.ggmlv3.q8_0.bin model.

Could you please provide assistance or any suggestions on why this might be occurring and how it could be mitigated? Is there a way to configure the application to utilize the GPU more heavily?

**Comment by quartet** [comment]
Update: The CPU utilization is actually like 50%.

**Comment by pseudotensor** [comment]
I would guess you didn't install llama_cpp_python for GPU usage?

i.e. in https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md#install :

![image](https://github.com/h2oai/h2ogpt/assets/2249614/1781d04d-4fdc-4439-a79e-9624cd933b08)

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/commit/80bb490d90fb61c6ee6b906f2dbd78c4242f4473

**Comment by quartet** [comment]
Recompiled llama did the trick for me. I can now see the GPU load working more with the CPU. 

Thanks!
